@echo off
cd /d "%~dp0"
echo Syncing content/posts/images -> static/images ...
python scripts\sync_images.py
echo Syncing my_icons -> static (favicons) ...
python scripts\sync_icons.py
echo Starting Hugo server...
hugo server -D --baseURL "http://localhost:1313/" --appendPort=false
